name: Bug Rapport
description: Meld een bug
title: "[Bug]: "
labels: ["bug"]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: Wat gebeurde er?
      description: Vertel ook wat had je verwacht dat er zou gebeuren.
      placeholder: Vertel ons wat je ziet!
      value: "Een bug!"
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevante logs
      description: Kopieer en plak eventuele relevante loguitvoer. Dit wordt automatisch opgemaakt als code, dus geen behoefte aan backticks.
      render: shell
